apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-w2
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: alpine
        command:
        - sleep
        - infinity