apiVersion: batch/v1
kind: Job
metadata:
  name: myjob-sync
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-2"
spec:
  template:
    spec:
      containers:
      - name: myapp
        image: alpine
        command:
        - sleep
        - "10"
      restartPolicy: Never