apiVersion: batch/v1
kind: Job
metadata:
  name: myjob-presync
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: myapp
        image: alpine
        command:
        - sleep
        - "10"
      restartPolicy: Never