apiVersion: batch/v1
kind: Job
metadata:
  name: myjob-presync
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: myapp
        image: alpine
        command:
        - /bin/sh
        args:
        - -c
        - sleep 5; pkill sleep
      - name: sidecar
        image: alpine
        command:
        - sleep
        - "30"
      restartPolicy: Never

      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL