apiVersion: batch/v1
kind: Job
metadata:
  name: myjob-postsync
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: alpine
        command:
        - sleep
        - "10"